### PR TITLE
RHMAP-10097 update to Swift 2.3

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@corinnekrych can you review?

**Comment by corinnekrych** [comment]
👁

**Comment by corinnekrych** [comment]
LGTM
@jcesarmobile  but let's do a PR on swift2.3 brnach

**Comment by jcesarmobile** [comment]
done

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
