### PR TITLE
Update FeedHenry SDK with RHMAP-12362 fix

### PR DESCRIPTION
**Pull request by jcesarmobile**

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@corinnekrych last one, can you take a look?

**Comment by corinnekrych** [comment]
@jcesarmobile are you going to release 4.2.1 prior to merge this PR and replaced by release number instead of pointing to repos tag?

**Comment by jcesarmobile** [comment]
Yeah, released 4.2.1 and updated the PR

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
